apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: authorizeddomainpolicy
spec:
  crd:
    spec:
      names:
        kind: AuthorizedDomainPolicy
      validation:
        legacySchema: true
        openAPIV3Schema:
          properties:
            domains:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{.Files.Get "rego/authorizeddomainpolicy/policy.rego" | indent 8 }}
