apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cats
spec:
  commonName: cats.local.mikesir87.training
  dnsNames:
    - cats.local.mikesir87.training
  secretName: cats-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats
spec:
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
        - name: cats
          image: mikesir87/cats:1.0
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /
              port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cats
spec:
  rules:
    - host: cats.local.mikesir87.training
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cats
              port: 
                number: 5000
  tls:
  - hosts:
      - cats.local.mikesir87.training
    secretName: cats-tls-cert  
---
apiVersion: v1
kind: Service
metadata:
  name: cats
spec:
  selector:
    app: cats
  ports:
    - port: 5000
