apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 5m0s
  url: https://open-policy-agent.github.io/gatekeeper/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 5m
  targetNamespace: gatekeeper-system
  chart:
    spec:
      chart: gatekeeper
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: gatekeeper-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true